### ISSUE TITLE
Unable to compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by reinvantveer** [MotorolaMobilityLLC/openocd#10]
I'm reading that flashing firmware to the MDK is done best using OpenOCD. Following the instructions on https://developer.motorola.com/documentation/setup-environment#embedded-firmware-development I'm getting this error:
```
$ ./bootstrap 
+ aclocal
+ libtoolize --automake --copy
+ autoconf
configure.ac:12: error: possibly undefined macro: AC_MSG_WARN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:240: error: possibly undefined macro: AC_MSG_NOTICE
configure.ac:342: error: possibly undefined macro: AC_DEFINE
```
Any ideas on this? Help greatly appreciated.

**Comment by BitWire** [comment]
you need to install pkg-config via "sudo apt install pkg-config"

**Comment by reinvantveer** [comment]
Yes that did it! It now compiles. `pkg-config` isn't listed in the requirements but it certainly seems a requirement. Thans @BitWire !
