### ISSUE TITLE
Unable to flash firmware: "** OpenOCD init failed **" 

### ISSUE THREAD

**Issue by reinvantveer** [MotorolaMobilityLLC/openocd#11]
Hi, after successfully compiling I'm unfortunately unable to flash my moto ref mod:

```
$ sudo openocd -f ~/Documents/Git/motomods/openocd/tcl/board/moto_mdk_muc_reset.cfg -c "program nuttx.tftf 0x08008000 reset exit"
[sudo] password for rein: 
Open On-Chip Debugger 0.10.0-dev-00347-gc2ee7b2c (2018-11-01-11:09)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : FTDI SWD mode enabled
srst_only separate srst_nogate srst_push_pull connect_deassert_srst
srst_only separate srst_nogate srst_push_pull connect_deassert_srst
adapter speed: 500 kHz
adapter_nsrst_delay: 100
srst_only separate srst_nogate srst_push_pull connect_deassert_srst
cortex_m reset_config sysresetreq
Info : clock speed 500 kHz
in procedure 'program' 
in procedure 'init' called at file "embedded:startup.tcl", line 473
in procedure 'ocd_bouncer'
** OpenOCD init failed **
shutdown command invoked
```
Obviously I've never tried this before but I'm using the example from https://developer.motorola.com/documentation/flashing-firmware#flashing-main-firmware-nuttx-
With some edits, however, since I didn't compile nuttx. Instead I'm reading the [moto_mdk_muc_reset.cfg configuration from the openocd repo](https://github.com/MotorolaMobilityLLC/openocd/blob/master/tcl/board/moto_mdk_muc_reset.cfg) (which I assume is identical, but I can't be sure).

The error message isn't very helpful in pointing to any particular direction on how to fix this. Any ideas?
Help greatly appreciated.

**Comment by reinvantveer** [comment]
Is it necessary to do something with the muc bootloader first? I.e. is the step referenced at https://developer.motorola.com/documentation/flashing-firmware#flashing-muc-bootloader mandatory? If so, then I have a new problem:
[muc-loader#8](https://github.com/MotorolaMobilityLLC/muc-loader/issues/8)

**Comment by SkyeOfBreeze** [comment]
For me, this seemed like an issue where the board was not properly powered based off of the solution I came up with.

The solution that works for me is to supply power to port 2 and use port 1 for the upload, assuming that switch B4 is OFF. Other solutions that may do the same thing is to set Switch B4 to ON (which allows power through port 1 to the board) and uploading code to the board while plugged into the back of the phone with switch B4 OFF (may not be reliable)

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
