### ISSUE TITLE
Misleading indentation or incorrect if statement

### ISSUE THREAD

**Issue by braindamagedman** [MotorolaMobilityLLC/openocd#8]
In file ./src/jtag/drivers/ftdi.c line 1152 block looks like incorrect:

```
if (ack == SWD_ACK_WAIT)
        ftdi_wait_encountered();
        ftdi_replay_queue(i);
goto skip;
```

Does the brackets missed?

**Comment by jwylder1** [comment]
Thanks,  You are right, the brackets appear to be missing.  Probably Dave was doing too much python coding:)

Will update (unless you would like to push the change, since you found it.)

Jim
